### ISSUE TITLE
Please help with this error

### ISSUE THREAD

**Issue by drashc** [danilopolani/rotating-proxy-python#1]

**Comment by drashc** [comment]
Traceback (most recent call last):   File "scrape_me.py", line 2, in <module>     from bs4 import BeautifulSoup ModuleNotFoundError: No module named 'bs4'

**Comment by NatLee** [comment]
pip install bs4

https://pypi.org/project/bs4/

**Comment by moustachedDev** [comment]
Yeah, It's that, If it doesn't resolve after that:
Create a virtual enviroment, install bs4 their & start working , search google on how to create virtual enviroment

**Comment by ribhupanwar** [comment]
how to use it in browser like 127.0.0.1 with port???
